import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import 'flowbite';
import './globals.css';
import I18nProvider from '@/providers/i18n-provider';

import { NavbarComponent } from '@/components/layout/nvabar.component';
import { FooterComponent } from '@/components/layout/footer.component';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <I18nProvider>
          <NavbarComponent />
          <div>{children}</div>
          <FooterComponent />
        </I18nProvider>
      </body>
    </html>
  );
}
